# Generated by Django 3.2.12 on 2022-03-24 10:39

import Music.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('A', 'Accept')], default='A', max_length=1)),
                ('music', models.FileField(upload_to='Music/songs')),
                ('image', models.ImageField(blank=True, upload_to=Music.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
