# Generated by Django 3.2.12 on 2022-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_length',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
