# Generated by Django 3.2.12 on 2022-03-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Singer', '0001_initial'),
        ('Music', '0002_music_music_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Singer.singer'),
        ),
    ]
