# Generated by Django 3.2.12 on 2022-03-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
        ('Music', '0003_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Album.album'),
        ),
    ]
