# Generated by Django 3.2.12 on 2022-04-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=1024),
        ),
        migrations.CreateModel(
            name='MusicViewsHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.ipaddress')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='hits',
            field=models.ManyToManyField(blank=True, through='Music.MusicViewsHit', to='Music.IPAddress'),
        ),
    ]
