# Generated by Django 3.2.12 on 2022-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_auto_20220403_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='views', through='Music.MusicViewsHit', to='Music.IPAddress'),
        ),
    ]
