# Generated by Django 3.2.12 on 2022-04-04 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0008_alter_music_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='Music.MusicViewsHit', to='Music.IPAddress'),
        ),
    ]
