# Generated by Django 3.2.12 on 2022-04-04 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0009_auto_20220404_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Music.music')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='music',
            name='user_playlist',
            field=models.ManyToManyField(blank=True, related_name='user_playlist', through='Music.PlayList', to=settings.AUTH_USER_MODEL),
        ),
    ]
