# Generated by Django 3.2.12 on 2022-04-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_auto_20220404_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['created_at']},
        ),
    ]
