# Generated by Django 3.2.12 on 2022-03-24 14:14

import Album.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=Album.models.upload_image_path)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Singer.singer')),
            ],
        ),
    ]
