# Generated by Django 3.2.12 on 2022-03-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Singer', '0001_initial'),
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='Singer.singer'),
        ),
    ]
