# Generated by Django 3.2.12 on 2022-03-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_alter_album_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
