# Generated by Django 3.2.12 on 2022-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Singer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
